# Generated by Django 2.0.2 on 2018-11-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181118_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='icon',
        ),
    ]
