# Generated by Django 2.0.2 on 2018-12-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationId',
            field=models.CharField(choices=[('BasundharaGate', 'L1'), ('ApoloHospital', 'L2'), ('MedehiMart', 'L3'), ('DblockMoszid', 'L4')], max_length=255),
        ),
    ]
